name: "Create a tag"
 
on: push
    
jobs:
  run-updater:
    runs-on: ubuntu-latest
    steps:
    - name: create a tag
      run: |
        curl --location --request POST 'https://api.coralogix.com/api/v1/external/tags/' \
        --header 'Authorization: Bearer ff8293bd-d224-45e6-9700-906fff09f2de' \
        --header 'Content-Type: application/json' \
        --data-raw '{ 
        "name": "'"${GITHUB_REF##*/}"'",
        "application": ["Goof-Platform"],
        "subsystem": ["subsystem"]
        }'
