name: "SBOM to CX"

on: push

jobs:
  run-updater:
    runs-on: ubuntu-latest
    steps:  
    - name: generate sbom results
      run: |
            curl -L -H "Accept: application/vnd.github+json" -H "Authorization: Bearer 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" -H "X-GitHub-Api-Version: 2022-11-28" https://api.github.com/repos/vberegov/goof-platform/dependency-graph/sbom > sbom.sarif
    - name: Upload file
      uses: actions/upload-artifact@v4
      with:
        path: |
            .
        compression-level: 0
    - name: upload sbom to CX
      run: |
            run: |
            curl -X POST 'https://ingress.coralogix.com/webhooks/v1/_hLsZCzkHFHkxB8sIXKbN?cx-api-key=cxtp_O8rQunc7vOLXpjVFaIRP6ifPA83VD1&cx-application-name=github&cx-subsystem-name=sbom' -H 'Content-Type: application/json' -d @sbom.sarif -v
