name: "SBOM to CX"

on: push

jobs:
  steps:  
   - name: generate sbom results
      run: |
            curl -L -H "Accept: application/vnd.github+json" -H "Authorization: Bearer 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" -H "X-GitHub-Api-Version: 2022-11-28" https://api.github.com/repos/vberegov/goof-platform/dependency-graph/sbom > sbom.json
