name: SBOM Generator

on:
  push
jobs:
  build:
    runs-on: ubuntu-latest
    permissions: read-all
    steps:
      - uses: actions/checkout@v3
      - uses: advanced-security/sbom-generator-action@v0.0.1
        id: sbom
        env: 
          GITHUB_TOKEN: ${{ github.token }}
      - uses: actions/upload-artifact@v3.1.0
        with: 
          path : ${{steps.sbom.outputs.fileName }}
          name : sbom.json
          compression-level: 0
      - run: | 
            more /home/runner/work/goof-platform/goof-platform/*.json
      - run: | 
            curl -X POST 'https://ingress.coralogix.com/webhooks/v1/_hLsZCzkHFHkxB8sIXKbN?cx-api-key=cxtp_O8rQunc7vOLXpjVFaIRP6ifPA83VD1&cx-application-name=github&cx-subsystem-name=sbom' -H 'Content-Type: application/json' -d @/home/runner/work/goof-platform/goof-platform/*.json -v 
