name: SBOM Generator

on:
  push
jobs:
  build:
    runs-on: ubuntu-latest
    permissions: read-all
    steps:
      - uses: actions/checkout@v3
      - uses: advanced-security/sbom-generator-action@v0.0.1
        id: sbom
        env: 
          GITHUB_TOKEN: ${{ github.token }}
      - uses: actions/upload-artifact@v4
        with: 
          path : ${{steps.sbom.outputs.fileName }}
          compression-level: 0
          name : sbom
      - run: | 
            unset env github
      - run: | 
            github=$(grep -m 1 "name" sbom.json)| jq '.sbom.packages[] | {"sbom":{packagename:.name,versionInfo:.versionInfo,licenseDeclared:.licenseDeclared,downloadLocation:.downloadLocation,licenseConcluded:.licenseConcluded,copyrightText:.copyrightText,SPDXID:.SPDXID,'$github'}}' sbom.json > sbom_output.json
      - run : | 
            echo $github
      - run: |
            mkdir sbom_chunks
      - run: | 
            split -l 11 sbom_output.json sbom_chunks/sbom
      - run: | 
            ls sbom_chunks/ > files_list
      - run: |
            echo "split completed"
      - run: | 
            set input_file="files_list"
      - run: | 
            while IFS= read -r line || [ -n "$line" ]; do
            curl -X POST 'https://ingress.coralogix.com/webhooks/v1/_hLsZCzkHFHkxB8sIXKbN?cx-api-key=cxtp_O8rQunc7vOLXpjVFaIRP6ifPA83VD1&cx-application-name=github&cx-subsystem-name=sbom' -H 'Content-Type: application/json' -d @"sbom_chunks/""$line" -v
            done < "$input_file"
