name: SBOM Generator

on:
  push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: advanced-security/sbom-generator-action@v0.0.1
        id: sbom
        env: 
          GITHUB_TOKEN: ${{ github.token }}
      - uses: actions/upload-artifact@v4
        with: 
          path : ${{steps.sbom.outputs.fileName }}
          compression-level: 0
          name : sbom
      - name: 'Setup jq'
        uses: dcarbone/install-jq-action@v2
        with:
          version: '${{ inputs.version }}'
          force: '${{ inputs.force }}'

      - name: 'Check jq'
        # language=sh
        run: |
          which jq
          jq --version
      - run: | 
          mv spdx*.spdx.json sbom.json
          cat sbom.json| jq -r '.packages[]? | {"sbom":{packagename:.name,versionInfo:.versionInfo,licenseDeclared:.licenseDeclared,downloadLocation:.downloadLocation,licenseConcluded:.licenseConcluded,copyrightText:.copyrightText,SPDXID:.SPDXID,referenceLocator:.externalRefs[].referenceLocator,referenceCategory:.externalRefs[].referenceCategory,referenceType:.externalRefs[].referenceType}}' | while read -r repo; do echo "$repo"; done | jq -r tostring |  jq -s '.' > sbom_output.json
          curl -X POST 'https://ingress.coralogix.com/webhooks/v1/_hLsZCzkHFHkxB8sIXKbN?cx-api-key=cxtp_O8rQunc7vOLXpjVFaIRP6ifPA83VD1&cx-application-name=github&cx-subsystem-name=sbom' -H 'Content-Type: application/json' -d @sbom_output.json -v
