name: SBOM Generator

on:
  push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: advanced-security/sbom-generator-action@v0.0.1
        id: sbom
        env: 
          GITHUB_TOKEN: ${{ github.token }}
      - uses: actions/upload-artifact@v4
        with: 
          path : ${{steps.sbom.outputs.fileName }}
          compression-level: 0
          name : sbom
      - name: 'Setup jq'
        uses: dcarbone/install-jq-action@v2
        with:
          version: '${{ inputs.version }}'
          force: '${{ inputs.force }}'

      - name: 'Check jq'
        # language=sh
        run: |
          which jq
          jq --version
      - run: | 
          chmod +x split.sh
          ./split.sh
