name: "Snyk Code Scan"

on:
  push:
    branches: [ main ]
  pull_request:
    # The branches below must be a subset of the branches above
    branches: [ main ]
  schedule:
    - cron: '32 4 * * 4'

jobs:
  Pipeline-Job:
    # Configure Environment
    name: 'Snyk Code Scan'
    runs-on: ubuntu-latest
    env: 
      SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
       
    steps:
    # Checkout Code
    - name: Checkout Code
      uses: actions/checkout@v1

    # Install and Authenticate to Snyk #2
    - name: Install Snyk & Authenticate
      run: |
         sudo npm install -g snyk
         snyk auth ${SNYK_TOKEN}
    # Run Snyk Code #3
    - name: Run Snyk Code
      run: |
         snyk code test --sarif  > results1.sarif
      continue-on-error: true
    - name: Upload SARIF file
      uses: github/codeql-action/upload-sarif@v1
      with:
        # Path to SARIF file relative to the root of the repository #4
        sarif_file: results1.sarif
